### ISSUE TITLE
npm ERR! shasum check failed

### ISSUE THREAD

**Issue by jeffm13** [krakenjs/kappa#111]
Using the latest kappa, installed on an EC2 server running under Docker (burkostya/npm-registry). We're consistently getting the "npm ERR! shasum check failed" error on random packages proxied from npmjs.org. I did an npm cache clean on clients, set the timeout option on the server (and restarted), and we still get the error on virtually all npm installs. Any hints?

**Comment by jasisk** [comment]
Which version of kappa are you using?

That sort of a response is generally due to either the cache (as you mentioned) or the request exceeding public npm's socket timeout (20s). If you're on a version before v1.0.0-rc.10, it means the response between your EC2 instance and the public registry is exceeding 20s (not likely). If you're on rc.10 or rc.11, the response is streamed which means your client isn't able to fetch the module in 20s. Does that duration seem about right?

**Comment by jeffm13** [comment]
Sorry. Moved over to Sinopia.

**Comment by acl0056** [comment]
I have a similar symptom. My problem is that after updating, vhost appears to be broken.  I get the checksum error because kappa is not writing the vhost, and npm is attempting to download `http://localhost:8200/something/-/something-2.0.4.tgz`.  And the server I am installing on is serving a page for port 8200.

**Comment by jasisk** [comment]
Hey acl0056,

mind opening a new issue? Yours seems unrelated (though still valid)—this issue dealt with package downloads that exceed 20 seconds being terminated indiscriminately.
