### ISSUE TITLE
HEAD Requests

### ISSUE THREAD

**Issue by scott2449** [krakenjs/kappa#99]
Hey @jeffharrell, Scott from Dow Jones

 Does kappa support HEAD requests? 

I see it in the docs but not the plugin code. I have a local instance that throws 500s on HEAD and our company instance just hangs. I ask because we are migrating to artifactory and they check all the packages with HEAD before proceeding (and of course NPM supports HEAD).

**Comment by jasisk** [comment]
Hi Scott. Despite the docs, we currently expect a response body from the proxied registries so HEAD requests will fail (as you've witnessed). I'm qualifying this as a bug and am working on a fix.

**Comment by scott2449** [comment]
@jasisk thanks, greatly appreciated.

**Comment by jasisk** [comment]
@scott2449 the fix for this has landed on the `rc` distribution as `1.0.0-rc.9`.  I wanted to give this a good thrashing internally before pushing it to latest however my initial impression is this is good to go. If you're up for it, you can install it with either:

`npm install kappa@rc` or `npm install kappa@1.0.0-rc.9`.

Either way, I'll let drop a note here when we move this to `latest`.

**Comment by scott2449** [comment]
Awesome. I'll ask the team that manages our npm if they can give this a shot.

**Comment by jasisk** [comment]
@scott2449 it's been stable for us for a while so I've moved this release to the `latest` dist-tag. In other words, this version is now available when you `npm install kappa`.
